### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by c1328** [rubiojr/go-edistribucion#1]
Hi! I'd like to use this adapter but I get some errors:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/rubiojr/go-edistribucion.(*Client).Login(0xc000080550)
	/root/go-edistribucion/edistribucion.go:314 +0x84e
main.main()
	/root/go-edistribucion/cmd/edistribucion/main.go:18 +0xce
```

Any idea?
`go version go1.20.5 linux/amd64
`

At the end I want to send the result to ioBroker, maybe you can push me in another direction if this adapter here is not maintained anymore. Thanks!

**Comment by rubiojr** [comment]
👋 a bit late, but fixed!
